name: Build and Publish LaTeX CVs
on: [push, pull_request, workflow_dispatch]
jobs:
  build_latex:
    strategy:
      fail-fast: true
      matrix:
        include:
          - root: en
          - root: fr
    name: "Build CV (${{ matrix.root }})"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ matrix.root }}.tex
          latexmk_shell_escape: true
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Curriculum Vitae
          path: |
            ./${{ matrix.root }}.pdf
