name: Build and Publish LaTeX CVs
on: [push, pull_request, workflow_dispatch]
jobs:
  build_latex:
    name: "Build CV"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: en.tex
          latexmk_shell_escape: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: fr.tex
          latexmk_shell_escape: true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Curriculum Vitae
          path: |
            ./*.pdf
